[#ftl]
[#-- @implicitly included --]
[#-- @ftlvariable name="initializeMemorySize" type="java.lang.Number" --]
[#-- @ftlvariable name="currentUrl" type="java.lang.String" --]
[#-- @ftlvariable name="file" type="cn.keking.model.FileAttribute" --]
[#-- @ftlvariable name="fileName" type="java.lang.String" --]
[#-- @ftlvariable name="fileTree" type="java.lang.String" --]
[#-- @ftlvariable name="needFilePassword" type="java.lang.Boolean" --]
[#-- @ftlvariable name="filePasswordError" type="java.lang.Boolean" --]
[#-- @ftlvariable name="baseUrl" type="java.lang.String" --]
[#-- @ftlvariable name="imgUrls" type="java.util.List<String>"--]
[#-- @ftlvariable name="textData" type="java.lang.String" --]
[#-- @ftlvariable name="xmlContent" type="java.lang.String" --]
[#-- @ftlvariable name="textContent" type="java.lang.String" --]
[#-- @ftlvariable name="textType" type="java.lang.String" --]
[#-- @ftlvariable name="markdown" type="java.lang.String"--]
[#-- @ftlvariable name="xml" type="java.lang.String"--]
[#-- @ftlvariable name="switchDisabled" type="java.lang.Boolean"--]
[#-- @ftlvariable name="watermarkAngle" type="java.lang.String"--]
[#-- @ftlvariable name="watermarkHeight" type="java.lang.String"--]
[#-- @ftlvariable name="watermarkWidth" type="java.lang.String"--]
[#-- @ftlvariable name="watermarkAlpha" type="java.lang.String"--]
[#-- @ftlvariable name="watermarkColor" type="java.lang.String"--]
[#-- @ftlvariable name="watermarkFontsize" type="java.lang.String"--]
[#-- @ftlvariable name="watermarkFont" type="java.lang.String"--]
[#-- @ftlvariable name="watermarkYSpace" type="java.lang.String"--]
[#-- @ftlvariable name="watermarkXSpace" type="java.lang.String"--]
[#-- @ftlvariable name="watermarkTxt" type="java.lang.String"--]
[#-- @ftlvariable name="ordinaryUrl" type="java.lang.String"--]
