<HTML>

<HEAD>
  <TITLE>$$1</TITLE>
</HEAD>

<FRAMESET ROWS="*,42,2" BORDER=0 FRAMEBORDER=0 FRAMESPACING=0>
    <FRAME SRC="$$3show.pl" NAME="frame1" SCROLLING=yes  RESIZE MARGINWIDTH=0 MARGINHEIGHT=0 FRAMEBORDER=0>
    <FRAME SRC="$$3editpic.pl" NAME="frame3" SCROLLING=yes RESIZE MARGINWIDTH=0 MARGINHEIGHT=0 FRAMEBORDER=0>
    <FRAME SRC="$$3poll.pl" NAME="frame2" SCROLLING=no NORESIZE MARGINWIDTH=0 MARGINHEIGHT=0 FRAMEBORDER=0>
</FRAMESET>

<NOFRAMES>

<BODY BGCOLOR="white">
    <META HTTP-EQUIV="-REFRESH" CONTENT="1;URL=$$3show.pl">
</BODY>
</HTML>
